
name: unification-xd

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DerivingStrategies
- LambdaCase
- MonoLocalBinds
- NoFieldSelectors
- OverloadedRecordDot
- TemplateHaskell
- UndecidableInstances

language: GHC2021

dependencies:
- base
- containers
- polysemy

library:
  source-dirs:
  - src